# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NiceTone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NiceTone

pod 'MeterGauge', :git => 'git@github.com:boof-tech/MeterGauge.git', :tag => '0.1.4'

end
